### ISSUE TITLE
Overall discussion

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/chaoss-microtasks#1]
If you have any questions regarding the micro-tasks, you can report it here. I would be happy to answer them. :slightly_smiling_face:

**Comment by valeriocos** [comment]
Thank you @vchrombie for preparing the proposal. Could you open an issue per micro-task, so we can have a dedicate space to discuss each micro-task ? thank you

@aswanipranjal given your experience in working with Perceval, would you like to start the reviewing of the micro-tasks ? what do you think ? :)

**Comment by vchrombie** [comment]
Sure, @valeriocos. I will be doing it now.

**Comment by valeriocos** [comment]
great! thank you @vchrombie for the prompt reply! :)

**Comment by vchrombie** [comment]
@valeriocos @aswanipranjal 
I have a doubt, is it good to have the microtasks code with OOPS in python?

Currently, I wrote the code just by defining functions and showing the results in the end, like a python script.

**Comment by vchrombie** [comment]
I see that the final [implementations](https://github.com/chaoss/wg-gmd/tree/master/implementations) are in a perfect OOPS manner. So, I was thinking if I can write the microtasks using OOPS, it would be a good.

What do you say? @valeriocos @aswanipranjal

**Comment by aswanipranjal** [comment]
@valeriocos, @vchrombie, sorry about the late reply. 

@vchrombie I'll be reviewing the tasks shortly. Mean while, the OOPs approach sounds reasonable, so I think you can go ahead with that.

**Comment by vchrombie** [comment]
> @valeriocos, @vchrombie, sorry about the late reply.

No issues. :slightly_smiling_face: 

> @vchrombie I'll be reviewing the tasks shortly. Mean while, the OOPs approach sounds reasonable, so I think you can go ahead with that.

Thanks for the suggestion @aswanipranjal.

**Comment by vchrombie** [comment]
> @vchrombie I'll be reviewing the tasks shortly. Mean while, the OOPs approach sounds reasonable, so I think you can go ahead with that.

@aswanipranjal, I completed this for microtask 3, 4, 5, 6. I will be doing for the remaining too.
Please review them when you get free time. :slightly_smiling_face:

**Comment by vchrombie** [comment]
@valeriocos @aswanipranjal 
I would like to ask if there are any comments or suggestions for the microtasks. You can have a look if you are free.

I know the GSoC submissions are over but there is always time for improvement. :slightly_smiling_face:

**Comment by valeriocos** [comment]
Thank you @vchrombie for the effort, the microtasks and the explanations look good.  
As a minor comment, you could modify the formatting of `microtask-6` in the [List of microtasks](https://github.com/vchrombie/chaoss-microtasks#list-of-microtasks), since in the current status it seems that the task wasn't completed. Probably this formatting would be better:

- [x] [microtask-6](microtask-6/) (optional)

what do you think ?

**Comment by vchrombie** [comment]
Closing all the issues in this repo. :slightly_smiling_face:

**Comment by valeriocos** [comment]
Perfect, thanks @vchrombie !!
